generic-service:
  nameOverride: hmpps-learner-records-api
  productId: "DPS121" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4
  serviceAccountName: hmpps-learner-records

  image:
    repository: ghcr.io/ministryofjustice/hmpps-learner-records-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-learner-records-api-cert
    annotations:
      nginx.ingress.kubernetes.io/limit-rpm: "120"

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    LRS_CONNECT_TIMEOUT: "20"
    LRS_WRITE_TIMEOUT: "20"
    LRS_READ_TIMEOUT: "20"

  volumeMounts:
    - mountPath: "/certs"
      name: dfe-lrs-api-cert

  volumes:
    - name: dfe-lrs-api-cert
      secret:
        secretName: dfe-lrs-api-cert

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    app-config-variables:
      ORG_PASSWORD: "ORG_PASSWORD"
      PFX_FILE_PASSWORD: "PFX_FILE_PASSWORD"
      UK_PRN: "UK_PRN"
      VENDOR_ID: "VENDOR_ID"
      HMPPS_SQS_QUEUES_AUDIT_QUEUE_NAME: "SQS_QUEUE_NAME"
      rds-postgresql-instance-output:
        RDS_INSTANCE_ENDPOINT: "rds_instance_endpoint"
        DATABASE_NAME: "database_name"
        DATABASE_USERNAME: "database_username"
        DATABASE_PASSWORD: "database_password"

  allowlist:
    groups:
      - global_protect
      - moj_cloud_platform

generic-prometheus-alerts:
  targetApplication: hmpps-learner-records-api
