hmpps-auth:
  url: "http://hmpps-auth:8080/auth"

lrs:
  base-url: "http://lrs-api:8080"
  pfx-path: "WebServiceClientCert.pfx"
  connectTimeoutSeconds: 20
  writeTimeoutSeconds: 20
  readTimeoutSeconds: 20