hmpps-auth:
  url: "http://hmpps-auth:8080/auth"

lrs:
  base-url: "http://lrs-api:8080"
  pfx-path: "WebServiceClientCert.pfx"
  ukprn: ${UK_PRN}
  orgPassword: ${ORG_PASSWORD}
  vendorId: ${VENDOR_ID}
  connectTimeout: ${LRS_CONNECT_TIMEOUT:20}
  writeTimeout: ${LRS_WRITE_TIMEOUT:20}
  readTimeout: ${LRS_READ_TIMEOUT:20}
