hmpps-auth:
  url: "http://hmpps-auth:8080/auth"

prisoner:
  search:
    api:
      endpoint:
        url: "https://prisoner-search-dev.prison.service.justice.gov.uk"

lrs:
  base-url: "http://lrs-api:8080"
  pfx-path: "WebServiceClientCert.pfx"
  ukprn: ${UK_PRN:}
  orgPassword: ${ORG_PASSWORD:}
  vendorId: ${VENDOR_ID:}
  connectTimeout: ${LRS_CONNECT_TIMEOUT:20}
  writeTimeout: ${LRS_WRITE_TIMEOUT:20}
  readTimeout: ${LRS_READ_TIMEOUT:20}

api:
  client:
    admin:
      id: ${API_CLIENT_ADMIN_ID:}
      secret: ${API_CLIENT_ADMIN_SECRET:}

hmpps.sqs:
  provider: localstack
  queues:
    audit:
      queueName: audit-queue
  localstackUrl: http://localstack-sqs:4566

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
