---
# Per environment values which override defaults in hmpps-learner-records-api/values.yaml

generic-service:
  ingress:
    host: learner-records-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    # Update the LRS URL to Point to Production
    LRS_BASE_URL: "https://cmp-ws.dev.lrs.education.gov.uk"
    LRS_PFX_PATH: "/certs/WebServiceClientCert.pfx"
    HMPPS_SQS_USE_WEB_TOKEN: "true"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: education-alerts
